# Generated by Django 5.2.6 on 2025-10-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_inspection_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='location_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='total_location_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
